export const ERROR_CODES = {
  USER_EMAIL_TAKEN: 'USER.EMAIL_TAKEN',
  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_HAS_DEPENDENCIES: 'USER.HAS_DEPENDENCIES',
} as const;

export const COMMON_ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
} as const;
